### ISSUE TITLE
Migration fails with Redmine 1.0 and Postgres 8.4

### ISSUE THREAD

**Issue by hwinkel** [AlekSi/redmine_code_review#1]
Hi, just tried this plugin, but it fails while running the migration (and also dont let revole the migration to VERSION=0)

The rake output looks like this:

Migrating redmine_code_review...
==  AddAutoAssign: migrating ==================================================
-- add_column(:code_review_project_settings, "auto_assign", :text)
rake aborted!
An error has occurred, this and all later migrations canceled:

PGError: ERROR:  relation "code_review_project_settings" does not exist
: ALTER TABLE "code_review_project_settings" ADD COLUMN "auto_assign" text

**Comment by AlekSi** [comment]
Hi. Please report this issue to upstream – this is just a mirror.

**Comment by hwinkel** [comment]
done, sorry
