### ISSUE TITLE
REST API for automatic review request creation

### ISSUE THREAD

**Issue by ghost** [AlekSi/redmine_code_review#3]
Is there any possibility of creating review requests over REST API like for example issues [1]?

We would like to personalize automatic review request creation (like one review request per `git push`, different reviewer for different developer, etc.).

I can create new issue in *Review* tracker with [1] but I am not able to link "Review assigned for" changeset.

Thanks for ideas!

[1]: http://www.redmine.org/projects/redmine/wiki/Rest_Issues

**Comment by AlekSi** [comment]
Sorry, this repository is not maintained – I'm not following Redmine development and not writing Ruby code for years.

**Comment by AlekSi** [comment]
Also, note that repository was a mirror. Maybe upstream is still there somewhere.

**Comment by AlekSi** [comment]
I think it is https://github.com/haru/redmine_code_review
